services:
  db:
    build:
      context: ./db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  # Expose for local dev; internal container port must be 5432
    networks:
      - backend

  app1:
    build:
      context: ./app1
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      API_SERVER_PORT: ${API_SERVER_PORT}
    ports:
      - "${API_SERVER_PORT}:8080"
    networks:
      - backend

networks:
  backend: